backend:
  build: ./backend
  expose:
    - "80"
  command: python manage.py runserver 0.0.0.0:80
web:
  build: .
  command: node private/server.js
backend:
  build: ./backend
  expose:
    - "80"
  command: python manage.py runserver 0.0.0.0:80
web:
  build: .
  command: node private/server.js
  links:
    - backend
  ports: 
    - "8080:8080"