# Generated by Django 2.0.3 on 2018-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('submissionDate', models.DateField()),
                ('upload', models.FileField(upload_to='assignment/')),
                ('last_upload', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.TextField()),
                ('courseCode', models.TextField()),
                ('description', models.TextField()),
                ('assessment', models.TextField()),
            ],
            options={
                'db_table': 'course_info',
            },
        ),
        migrations.CreateModel(
            name='LTNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('upload', models.FileField(upload_to='ltNote/')),
                ('last_upload', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'lt_note',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('location', models.TextField()),
                ('lecturer', models.IntegerField()),
                ('extra', models.TextField()),
            ],
            options={
                'db_table': 'teaching_staff',
            },
        ),
        migrations.CreateModel(
            name='TutorialNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('upload', models.FileField(upload_to='tutorialNote/')),
                ('last_upload', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tutorial_note',
            },
        ),
    ]
