# Generated by Django 2.0.5 on 2018-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('last_upload', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_token',
            },
        ),
    ]
